trigger:
- master

pool: Newpool  # Your self-hosted agent pool

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'

steps:
- script: |
    choco install python --version=$(python.version) -y
  displayName: 'Install Python $(python.version) using Chocolatey'

- task: UsePythonVersion@0  # Use the available version
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install robotframework robotframework-requests robotframework-jsonlibrary robotframework-seleniumlibrary robotframework-pabot
  displayName: 'Install dependencies'

- script: |
    robot -d results testcases/grocery.robot  # Execute the specified Robot file
  displayName: 'Run Robot Framework Test: grocery.robot'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'results'  # Path to the results folder
    artifact: 'RobotResults'  # Name for published artifact
    publishLocation: 'pipeline'
  displayName: 'Publish Robot Framework Test Results'
