trigger:
- master

pool: Newpool

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'

steps:
- script: |
    echo "Using pre-installed Python version $(python.version) on the self-hosted agent"
  displayName: 'Verify Python Version'

- script: |
    python -m pip install --upgrade pip
    pip install robotframework robotframework-requests robotframework-jsonlibrary robotframework-seleniumlibrary robotframework-pabot
  displayName: 'Install dependencies'

- script: |
    robot -d results testcases/grocery.robot  # Execute the specified Robot file
  displayName: 'Run Robot Framework'